export const SET_CHARACTERS = 'SET_CHARACTERS';
export const SET_CHARACTERS_DETAILS = 'SET_CHARACTERS_DETAILS';
export const SET_COMICS = 'SET_COMICS';
export const SET_COMIC = 'SET_COMIC';
export const SET_FAVORITES = 'SET_FAVORITES';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const ON_LOADING = 'ON_LOADING';
export const ON_LOADING_MODAL = 'ON_LOADING_MODAL';
